# Generated by Django 3.2.16 on 2023-04-09 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_feedbacks'),
    ]

    operations = [
        migrations.CreateModel(
            name='sreview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.CharField(max_length=50)),
                ('reviews', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=50)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.customerr')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.services')),
            ],
        ),
        migrations.CreateModel(
            name='sfeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.CharField(max_length=225)),
                ('date', models.CharField(max_length=225)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.customerr')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.services')),
            ],
        ),
    ]
